### ISSUE TITLE
Time zone designator without double colon doesn't work

### ISSUE THREAD

**Issue by buschtoens** [csnover/js-iso8601#27] opened 2016-06-15 09:33 UTC
Consider this date:

```
2016-06-15T10:54:34.000+0200 vs 2016-06-15T10:54:34.000+02:00
```

The regex is missing a `?` to make the double colon optional, [as it is allowed by the standard](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators).
```
^(\d{4}|[+\-]\d{6})(?:-(\d{2})(?:-(\d{2}))?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{3}))?)?(?:(Z)|([+\-])(\d{2})(?::(\d{2}))?)?)?$
```

Correct regex would be:
```
^(\d{4}|[+\-]\d{6})(?:-(\d{2})(?:-(\d{2}))?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{3}))?)?(?:(Z)|([+\-])(\d{2})(?::?(\d{2}))?)?)?$
```

**Comment by buschtoens** [comment] 2016-06-15 09:35
Do you want a PR?

**Comment by csnover** [comment] 2016-06-15 13:16
Duplicate of https://github.com/csnover/js-iso8601/issues/25.

**Closed by csnover** 2016-06-15 13:16 UTC
